title: OpenSourceFeed
email: niyasmonc@gmail.com
description: >-
  Gallery of GNU/Linux, BSD, and other open-source distributions and open source
  desktop environments with updates & stories on each.
baseurl: ''
url: 'https://www.opensourcefeed.org'
caption: Free Operating Systems & Desktop Environments
twitter_username: opensourcefeed
github_username: opensourcefeed
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
permalink: ':title/'
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
twitter:
  username: opensourcefeed
facebook:
  publisher: opensourcefeed
social:
  name: OpenSourceFeed
  links:
    - 'https://plus.google.com/b/114426521113195641057/'
    - 'https://twitter.com/opensourcefeed'
    - 'https://www.facebook.com/opensourcefeed'
webmaster_verifications:
  google: 8-DkVd0YN5zpN1NpF6X4SMnRckVNQgEu4O8Uk9cU_2c
paginate: 18
paginate_path: '/blog/:num/'
future: true
